[package]
name = "cowrie"
version = "1.0.0"
authors = []

[addresses]
cowrie = "0x9b81f7c089535e3cdd6f4b985461cf4beb2b548726815b2e961facd58fae0b8b"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]